### PR TITLE
feat: Implemented metrics exposure for job status with labels: name, namespace, uid, status, reason

### PR DESCRIPTION
**Pull request by 13241308289**
### Ⅰ. Describe what this PR does

feat: Implemented metrics exposure for job status with labels: name, namespace, uid, status, reason

### II. Does this pull request fix one issue?

feat: #309

### CODE REVIEW

**Comment by SimonCqk** [comment]
@13241308289 hi, thanks for your contribution, anyway some CI checks failed, would you fix it and push again ?

**Comment by 13241308289** [comment]
> @13241308289 hi, thanks for your contribution, anyway some CI checks failed, would you fix it and push again ?

yeah， I will fix it and push again

**Comment by 13241308289** [comment]
> @13241308289 hi, thanks for your contribution, anyway some CI checks failed, would you fix it and push again ?

Since the exposed metrics are dependent on specific services, it's not feasible to write test cases for them. The issue with CI is that these cases cannot be covered in tests. However, I have already employed this in our production environment.

**Comment by SimonCqk** [comment]
> > @13241308289 hi, thanks for your contribution, anyway some CI checks failed, would you fix it and push again ?
> 
> Since the exposed metrics are dependent on specific services, it's not feasible to write test cases for them. The issue with CI is that these cases cannot be covered in tests. However, I have already employed this in our production environment.

I got you, metrics related code is hard to cover UT, however, would you refine the go-lint hinted code and let this CI task pass?

**Comment by 13241308289** [comment]
> > > @13241308289 hi, thanks for your contribution, anyway some CI checks failed, would you fix it and push again ?
> > 
> > 
> > Since the exposed metrics are dependent on specific services, it's not feasible to write test cases for them. The issue with CI is that these cases cannot be covered in tests. However, I have already employed this in our production environment.
> 
> I got you, metrics related code is hard to cover UT, however, would you refine the go-lint hinted code and let this CI task pass?

okk, I understand, I modify and push again， check has paased

**Pull request merged**
