### PR TITLE
forget return when error happens

### PR DESCRIPTION
**Pull request by kerthcet**
Signed-off-by: kerthcet <kerthcet@gmail.com>

### Ⅰ. Describe what this PR does
forget to return when error happens && some tiny typos found when reading sourcecode

### II. Does this pull request fix one issue?

None

### III. Special notes for reviewers if any.
New to Kubedl

### CODE REVIEW

**Comment by kerthcet** [comment]
kindly ping @SimonCqk

**Comment by jian-he** [comment]
lgtm

**Comment by jian-he** [comment]
thanks for your contribution ! @kerthcet

**Pull request merged**
