### PR TITLE
refactor: optimize log level and go-imports.

### PR DESCRIPTION
**Pull request by SimonCqk**
Signed-off-by: SimonCqk <cqk0100@gmail.com>

### Ⅰ. Describe what this PR does

1. optimize log level when job not found in informer cache, fix issue #199 
2. ~~optimize go-imports~~

### CODE REVIEW

**Comment by jian-he** [comment]
can we do the go imports changes in a separate issue ?

**Comment by jian-he** [comment]
UT failed.

different loggers are used across the code. klog or the controller-runtime builtin log, we also need to consolidate those later I think

**Comment by SimonCqk** [comment]
> can we do the go imports changes in a separate issue ?

ok, I will post another issue later

**Comment by SimonCqk** [comment]
> UT failed.
> 
> different loggers are used across the code. klog or the controller-runtime builtin log, we also need to consolidate those later I think

logger library consistency is indeed a problem, the output logging in stdout  is mixed with multiple formats, maybe use `klog` as our unified logger?

**Comment by jian-he** [comment]
lgtm

**Pull request merged**
