### PR TITLE
Feature/volcano scheduler

### PR DESCRIPTION
**Pull request by HeGaoYuan**
### Ⅰ. Describe what this PR does
[feature request] Add volcano scheduler as a new GangScheduler

### II. Does this pull request fix one issue?
https://github.com/kubedl-io/kubedl/issues/150

### III. Special notes for reviewers if any.
Also fix the batch_scheduler miss the annotation to relate pod to podGroup problem.

### CODE REVIEW

**Comment by SimonCqk** [comment]
add unit tests for your code :)

**Comment by HeGaoYuan** [comment]
> add unit tests for your code :)

sorry for that, I will add it

**Comment by jian-he** [comment]
lgtm, wait for the ut to merge in.
Thanks for your contribution !

**Comment by HeGaoYuan** [comment]
@SimonCqk @jian-he 
I have added the unit test of volcano scheduler and batch scheduler.
I also change the cos scheduler and it's unit test.
Trouble you to review it. Thanks.

**Comment by jian-he** [comment]
@HeGaoYuan Thanks !

**Pull request merged**
