### PR TITLE
manifests: add omitempty tag of job conditions in status

### PR DESCRIPTION
**Pull request by SimonCqk**
### Ⅰ. Describe what this PR does

fix: https://github.com/kubedl-io/kubedl/issues/181#issuecomment-925860037
update operations may throw errors when job conditions is empty.

### CODE REVIEW

**Comment by jian-he** [comment]
ut failure, @SimonCqk take a look

**Comment by HeGaoYuan** [comment]
@SimonCqk you missed "inject TypeMeta in defaulter functions as a preventive solution(https://github.com/kubedl-io/kubedl/issues/181#issuecomment-925579451)" ?

**Comment by HeGaoYuan** [comment]
@SimonCqk If you decide to add omitempty tag to job.status.conditions, you also need to add omitempty to job.status.replicaStatuses

**Comment by SimonCqk** [comment]
> @SimonCqk you missed "inject TypeMeta in defaulter functions as a preventive solution([#181 (comment)](https://github.com/kubedl-io/kubedl/issues/181#issuecomment-925579451))" ?

I’ll post another PR to fix this

**Comment by SimonCqk** [comment]
> @SimonCqk If you decide to add omitempty tag to job.status.conditions, you also need to add omitempty to job.status.replicaStatuses

Is it necessary? replicaStatuses will always be filled up with replicas states after reconciled

**Comment by jian-he** [comment]
@HeGaoYuan any more questions on this ?

**Comment by HeGaoYuan** [comment]
> > @SimonCqk If you decide to add omitempty tag to job.status.conditions, you also need to add omitempty to job.status.replicaStatuses
> 
> Is it necessary? replicaStatuses will always be filled up with replicas states after reconciled

You are right. Sorry, I am wrong.

**Comment by HeGaoYuan** [comment]
> @HeGaoYuan any more questions on this ?

no

**Comment by jian-he** [comment]
thanks @HeGaoYuan for the review, merge in

**Pull request merged**
